# ReElytras: v1.1
# Author: lluk

# Is it possible to accelerate on a trident using riptide enchantment or fireworks
# Default: true
allowRiptideBoost: true
allowFireworkBoost: true

# Is it possible to enchant the elytras on the anvil
# Default: true
allowEnchantments: true

# Is it possible to use a mending book on an elytra. This value will be ignored if allowEnchantments is false
# Default: true
allowMending: true

# Is it possible to use an unbreaking book on an elytra. This value will be ignored if allowEnchantments is false
# Default: true
allowUnbreaking: true

# Is it possible to repair elytras with the help of unification
# Default: true
allowUnificationRepairInAnvil: true
allowUnificationRepairInCraft: true
allowUnificationRepairInGrindstone: true

# Is it possible to repair elytras on the anvil using phantom membranes
# Default: true
allowRepairWithPhantomMembrane: true

# How many percent of the maximum durability will be repaired with a single phantom membrane
# Default: 25
repairWithPhantomMembranePercent: 25

# Will the sound of an item breaking be played when the elytras breaks
# Default: false
playDestroySound: false

# How much durability will be removed from the elytras per second
# Default: 1
damagePerSecond: 1

# The elytras will disappear from the player's inventory if they break down
# Default: false
permanentDestroy: false

# Is it possible to glide on elytras? The value is false to completely prohibit flight on elytras
# Default: true
allowElytras: true

# Is it possible to slide on the elytras during the rain?
# Default: true
allowElytrasWhenRaining: true